name: Terraform Apply

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      terraform-token:
        required: true
        type: string

jobs:
  apply:
    name: Apply
    environment: ${{ inputs.environment }}

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: environment
        name: Set Environment Variables
        run: |
          // Env vars needed for terraform cloud workflows
          echo "TF_WORKSPACE=${{ vars.TF_WORKSPACE }}" >> $GITHUB_ENV
          echo "TF_LOCAL_DIRECTORY=${{ vars.TF_DIRECTORY }}" >> $GITHUB_ENV
          echo "TF_CLOUD_ORGANIZATION=${{ vars.TF_ORGANIZATION }}" >> $GITHUB_ENV
          echo "TF_API_TOKEN=${{ inputs.terraform-token }}" >> $GITHUB_ENV

      - id: upload
        name: Upload
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: plan-upload
        with:
          workspace: ${{ vars.TF_WORKSPACE }}
          directory: ${{ vars.TF_DIRECTORY }}
          speculative: true

      - id: create
        name: Create
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: apply-run
        with:
          workspace: ${{ vars.TF_WORKSPACE }}
          configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
          plan_only: true

      - id: apply
        name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
