name: "Apply Cloud Deployment on Develop"

on:
  push:
    branches:
      - develop

env:
  TERRAFORM_CLOUD_ORGANIZATION: "property-fundamentals-dev"
  TERRAFORM_CLOUD_WORKSPACE: "property-fundamentals"
  TERRAFORM_CLOUD_API_TOKEN: "${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}"
  TERRAFORM_LOCAL_DIRECTORY: "property_fundamentals/infrastructure/dev/."

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: apply-upload
        with:
          workspace: ${{ env.TERRAFORM_CLOUD_WORKSPACE }}
          directory: ${{ env.TERRAFORM_LOCAL_DIRECTORY }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: apply-run
        with:
          workspace: ${{ env.TERRAFORM_CLOUD_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
