name: GCP Authentication

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      token:
        value: ${{ jobs.gcp-auth.outputs.token }}

jobs:
  gcp-auth:
    name: Generate authentication credentials
    environment: ${{ inputs.ENVIRONMENT }}
    outputs:
      token: ${{ steps.gcp-auth-encrypt.outputs.encrypted_token }}

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - id: gcp-auth-auth
        name: Authenticate
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          credentials_json: ${{ secrets.GCP_DOCKER_TOKEN }}
      
      - id: gcp-auth-encrypt
        name: Encrypt Token
        run: |
          TOKEN=${{ steps.gcp-auth-auth.outputs.access_token }};
          BINARY_TOKEN=$(echo -n "$TOKEN" | openssl enc -aes-256-cbc -pbkdf2 -salt -k "${{ secrets.GH_ENCRYPTION_PASSWORD }}");
          ENCRYPTED_TOKEN=$(echo -n "$BINARY_TOKEN" | base64);
          echo "encrypted_token=$ENCRYPTED_TOKEN" >> $GITHUB_OUTPUT
