name: "Reusable"

on:
  workflow_call:

jobs:
  reusable:
    name: "reusable"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: "test step"
      run: echo "test step"
