name: "Reusable"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  reusable:
    name: "reusable"
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: "test step"
        run: echo "${{ secrets.FAKE_SECRET }}"
