name: Terraform Authentication

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      token:
        value: ${{ jobs.terraform-auth.outputs.token }}

jobs:
  terraform-auth:
    name: Generate authentication credentials
    environment: ${{ inputs.ENVIRONMENT }}
    outputs:
      token: ${{ steps.terraform-auth-auth.outputs.token }}

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - id: terraform-auth-auth
        name: Authenticate
        run: |
          echo "token=${{ secrets.TERRAFORM_TOKEN }}" >> $GITHUB_OUTPUT
