name: Terraform Authentication

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      token:
        value: ${{ jobs.terraform-auth.outputs.token }}

jobs:
  terraform-auth:
    name: Generate authentication credentials
    environment: ${{ inputs.ENVIRONMENT }}
    outputs:
      token: ${{ steps.terraform-auth-encrypt.outputs.encrypted_token }}

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - id: terraform-auth-auth
        name: Authenticate
        run: |
          echo "token=${{ secrets.TF_TOKEN }}" >> $GITHUB_OUTPUT
      
      - id: terraform-auth-encrypt
        name: Encrypt Token
        run: |
          ENCRYPTED_TOKEN=$(echo -n "${{ steps.terraform-auth-auth.outputs.token }}" | openssl enc -A -aes-256-cbc -pbkdf2 -salt -k "${{ secrets.GH_ENCRYPTION_PASSWORD }}" | base64);
          echo "encrypted_token=$ENCRYPTED_TOKEN" >> $GITHUB_OUTPUT
