name: Test

on:
  push:
  # pull_request:
  #   branches:
  #     - develop

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: test
      run: |
        echo "made it"

  # Set the workflow environment
  set-environment:
    uses: .github/workflows/templates/environment.yaml
    with:
      branch-name: ${{ github.base_ref }}
    secrets: inherit
