name: "Test"

on:
  push:

jobs:
  set-environment:
    uses: ./.github/workflows/set-environment.yaml
    with:
      branch-name: develop
    secrets: inherit

  test:
    uses: ./.github/workflows/reusable.yaml
    with:
      environment: ${{ needs.set-environment.outputs.environment }}
    secrets: inherit
